-- ============================================================
-- 2091 직원 관리 테이블 DDL
-- Database: Oracle XE 21c (XEPDB1)
-- Schema: sunjin_admin
-- Generated: 2026-01-27
--
-- Note: All column names are UPPERCASE (unquoted) to match
-- Oracle's auto-uppercase convention for unquoted identifiers.
-- Use LVL instead of LEVEL (reserved word).
-- ============================================================

-- ============================================================
-- 0. DROP EXISTING OBJECTS (for re-execution)
-- ============================================================

/*
-- Run these if you need to drop existing tables:
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEE_HISTORY CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ACCOUNT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE POSITION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DEPARTMENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE POSITION_CODE_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
COMMIT;
*/

-- ============================================================
-- 1. SEQUENCES
-- ============================================================

-- 직급 코드 자동 생성용 시퀀스 (Decision #10)
-- START WITH 6 because initial data uses POS-00001 through POS-00005
CREATE SEQUENCE POSITION_CODE_SEQ START WITH 6 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ============================================================
-- 2. DEPARTMENT (부서) 테이블
-- ============================================================

CREATE TABLE DEPARTMENT (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME VARCHAR2(100) NOT NULL,
  CODE VARCHAR2(20) NOT NULL,
  DESCRIPTION VARCHAR2(500),
  PARENT_DEPARTMENT_ID NUMBER,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  DELETED_AT TIMESTAMP,
  CONSTRAINT FK_DEPARTMENT_PARENT FOREIGN KEY (PARENT_DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);

-- 부서명 유니크 (soft delete 제외) - Function-based unique index
CREATE UNIQUE INDEX UQ_DEPARTMENT_NAME ON DEPARTMENT(CASE WHEN DELETED_AT IS NULL THEN NAME END);

-- 부서 코드 유니크 (soft delete 제외)
CREATE UNIQUE INDEX UQ_DEPARTMENT_CODE ON DEPARTMENT(CASE WHEN DELETED_AT IS NULL THEN CODE END);

-- 일반 인덱스
CREATE INDEX IDX_DEPARTMENT_PARENT ON DEPARTMENT(PARENT_DEPARTMENT_ID);
CREATE INDEX IDX_DEPARTMENT_DELETED ON DEPARTMENT(DELETED_AT);

-- ============================================================
-- 3. POSITION (직급) 테이블
-- ============================================================

-- Note: Use LVL instead of LEVEL (LEVEL is Oracle reserved word)
CREATE TABLE POSITION (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME VARCHAR2(50) NOT NULL,
  CODE VARCHAR2(20) NOT NULL,
  LVL NUMBER(2) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  DELETED_AT TIMESTAMP,
  CONSTRAINT CHK_POSITION_LEVEL CHECK (LVL BETWEEN 1 AND 10)
);

-- 직급명 유니크 (soft delete 제외)
CREATE UNIQUE INDEX UQ_POSITION_NAME ON POSITION(CASE WHEN DELETED_AT IS NULL THEN NAME END);

-- 직급 코드 유니크 (전체)
CREATE UNIQUE INDEX UQ_POSITION_CODE ON POSITION(CODE);

-- 일반 인덱스
CREATE INDEX IDX_POSITION_LEVEL ON POSITION(LVL);
CREATE INDEX IDX_POSITION_DELETED ON POSITION(DELETED_AT);

-- ============================================================
-- 4. EMPLOYEE (직원) 테이블
-- ============================================================

CREATE TABLE EMPLOYEE (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME VARCHAR2(100) NOT NULL,
  EMAIL VARCHAR2(255) NOT NULL,
  PHONE VARCHAR2(20),
  JOB_TITLE VARCHAR2(100),
  DEPARTMENT_ID NUMBER NOT NULL,
  POSITION_ID NUMBER NOT NULL,
  MANAGER_ID NUMBER,
  HIRED_AT TIMESTAMP NOT NULL,
  BIRTHDAY TIMESTAMP,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY_ID NUMBER,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY_ID NUMBER,
  DELETED_AT TIMESTAMP,
  CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID),
  CONSTRAINT FK_EMPLOYEE_POSITION FOREIGN KEY (POSITION_ID) REFERENCES POSITION(ID),
  CONSTRAINT FK_EMPLOYEE_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE(ID) ON DELETE SET NULL,
  CONSTRAINT FK_EMPLOYEE_CREATED_BY FOREIGN KEY (CREATED_BY_ID) REFERENCES EMPLOYEE(ID),
  CONSTRAINT FK_EMPLOYEE_UPDATED_BY FOREIGN KEY (UPDATED_BY_ID) REFERENCES EMPLOYEE(ID)
);

-- 이메일 유니크 (soft delete 제외)
CREATE UNIQUE INDEX UQ_EMPLOYEE_EMAIL ON EMPLOYEE(CASE WHEN DELETED_AT IS NULL THEN EMAIL END);

-- 일반 인덱스
CREATE INDEX IDX_EMPLOYEE_DEPARTMENT ON EMPLOYEE(DEPARTMENT_ID);
CREATE INDEX IDX_EMPLOYEE_POSITION ON EMPLOYEE(POSITION_ID);
CREATE INDEX IDX_EMPLOYEE_MANAGER ON EMPLOYEE(MANAGER_ID);
CREATE INDEX IDX_EMPLOYEE_HIRED ON EMPLOYEE(HIRED_AT);
CREATE INDEX IDX_EMPLOYEE_DELETED ON EMPLOYEE(DELETED_AT);
CREATE INDEX IDX_EMPLOYEE_NAME ON EMPLOYEE(NAME);

-- ============================================================
-- 5. ACCOUNT (계정) 테이블
-- ============================================================

CREATE TABLE ACCOUNT (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMPLOYEE_ID NUMBER NOT NULL,
  USERNAME VARCHAR2(50) NOT NULL,
  PASSWORD_HASH VARCHAR2(255) NOT NULL,
  ROLE VARCHAR2(20) DEFAULT 'USER' NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  LAST_LOGIN_AT TIMESTAMP,
  PASSWORD_CHANGED_AT TIMESTAMP,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  DELETED_AT TIMESTAMP,
  CONSTRAINT FK_ACCOUNT_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
  CONSTRAINT CHK_ACCOUNT_ROLE CHECK (ROLE IN ('ADMIN', 'MANAGER', 'USER')),
  CONSTRAINT CHK_ACCOUNT_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

-- 직원당 하나의 계정만 허용
CREATE UNIQUE INDEX UQ_ACCOUNT_EMPLOYEE ON ACCOUNT(EMPLOYEE_ID);

-- username 유니크 (soft delete 제외)
CREATE UNIQUE INDEX UQ_ACCOUNT_USERNAME ON ACCOUNT(CASE WHEN DELETED_AT IS NULL THEN USERNAME END);

-- 일반 인덱스
CREATE INDEX IDX_ACCOUNT_ACTIVE ON ACCOUNT(IS_ACTIVE);
CREATE INDEX IDX_ACCOUNT_ROLE ON ACCOUNT(ROLE);
CREATE INDEX IDX_ACCOUNT_DELETED ON ACCOUNT(DELETED_AT);

-- ============================================================
-- 6. EMPLOYEE_HISTORY (감사 로그) 테이블
-- ============================================================

CREATE TABLE EMPLOYEE_HISTORY (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMPLOYEE_ID NUMBER NOT NULL,
  CHANGE_TYPE VARCHAR2(20) NOT NULL,
  CHANGED_FIELDS CLOB,
  CHANGED_BY_ID NUMBER NOT NULL,
  CHANGED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_HISTORY_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
  CONSTRAINT FK_HISTORY_CHANGED_BY FOREIGN KEY (CHANGED_BY_ID) REFERENCES EMPLOYEE(ID),
  CONSTRAINT CHK_HISTORY_TYPE CHECK (CHANGE_TYPE IN ('CREATE', 'UPDATE', 'DELETE', 'DEACTIVATE'))
);

-- 일반 인덱스
CREATE INDEX IDX_HISTORY_EMPLOYEE ON EMPLOYEE_HISTORY(EMPLOYEE_ID);
CREATE INDEX IDX_HISTORY_CHANGED_AT ON EMPLOYEE_HISTORY(CHANGED_AT);
CREATE INDEX IDX_HISTORY_TYPE ON EMPLOYEE_HISTORY(CHANGE_TYPE);
CREATE INDEX IDX_HISTORY_EMPLOYEE_DATE ON EMPLOYEE_HISTORY(EMPLOYEE_ID, CHANGED_AT);

-- ============================================================
-- 7. 초기 데이터
-- ============================================================

-- 기본 부서 생성
-- Using UNISTR for Korean characters: 본사=\BCF8\C0AC, 본사 조직=\BCF8\C0AC \C870\C9C1
INSERT INTO DEPARTMENT (NAME, CODE, DESCRIPTION) VALUES (UNISTR('\BCF8\C0AC'), 'HQ', UNISTR('\BCF8\C0AC \C870\C9C1'));

-- 기본 직급 생성
-- 사원=\C0AC\C6D0, 대리=\B300\B9AC, 과장=\ACFC\C7A5, 차장=\CC28\C7A5, 부장=\BD80\C7A5
INSERT INTO POSITION (NAME, CODE, LVL) VALUES (UNISTR('\C0AC\C6D0'), 'POS-00001', 10);
INSERT INTO POSITION (NAME, CODE, LVL) VALUES (UNISTR('\B300\B9AC'), 'POS-00002', 8);
INSERT INTO POSITION (NAME, CODE, LVL) VALUES (UNISTR('\ACFC\C7A5'), 'POS-00003', 6);
INSERT INTO POSITION (NAME, CODE, LVL) VALUES (UNISTR('\CC28\C7A5'), 'POS-00004', 4);
INSERT INTO POSITION (NAME, CODE, LVL) VALUES (UNISTR('\BD80\C7A5'), 'POS-00005', 2);

COMMIT;

-- ============================================================
-- 8. 검증 쿼리
-- ============================================================

-- 테이블 목록 확인
SELECT table_name FROM user_tables
WHERE table_name IN ('DEPARTMENT', 'POSITION', 'EMPLOYEE', 'ACCOUNT', 'EMPLOYEE_HISTORY')
ORDER BY table_name;

-- 시퀀스 확인
SELECT sequence_name FROM user_sequences WHERE sequence_name = 'POSITION_CODE_SEQ';

-- 인덱스 수 확인
SELECT COUNT(*) AS index_count FROM user_indexes
WHERE table_name IN ('DEPARTMENT', 'POSITION', 'EMPLOYEE', 'ACCOUNT', 'EMPLOYEE_HISTORY');

-- 제약조건 수 확인
SELECT COUNT(*) AS constraint_count FROM user_constraints
WHERE table_name IN ('DEPARTMENT', 'POSITION', 'EMPLOYEE', 'ACCOUNT', 'EMPLOYEE_HISTORY');

-- 초기 데이터 확인
SELECT * FROM DEPARTMENT;
SELECT * FROM POSITION ORDER BY LVL;

-- ============================================================
-- Column Identifier Reference
-- ============================================================
/*
All columns use UPPERCASE (unquoted) identifiers:

DEPARTMENT: ID, NAME, CODE, DESCRIPTION, PARENT_DEPARTMENT_ID, CREATED_AT, UPDATED_AT, DELETED_AT
POSITION: ID, NAME, CODE, LVL, CREATED_AT, UPDATED_AT, DELETED_AT
EMPLOYEE: ID, NAME, EMAIL, PHONE, JOB_TITLE, DEPARTMENT_ID, POSITION_ID, MANAGER_ID,
          HIRED_AT, BIRTHDAY, CREATED_AT, CREATED_BY_ID, UPDATED_AT, UPDATED_BY_ID, DELETED_AT
ACCOUNT: ID, EMPLOYEE_ID, USERNAME, PASSWORD_HASH, ROLE, IS_ACTIVE,
         LAST_LOGIN_AT, PASSWORD_CHANGED_AT, CREATED_AT, UPDATED_AT, DELETED_AT
EMPLOYEE_HISTORY: ID, EMPLOYEE_ID, CHANGE_TYPE, CHANGED_FIELDS, CHANGED_BY_ID, CHANGED_AT

Note: Use LVL instead of LEVEL (Oracle reserved word)
*/
