services:
  app:
    container_name: sunjin-erp-app
    build: .
    ports:
      - "3200:3000"
    env_file:
      - .env
    networks:
      - sunjin-network
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 8G
    restart: unless-stopped

networks:
  sunjin-network:
    external: true
