// Generated: 2026-01-28 00:02:00 KST

import { MigrationInterface, QueryRunner } from 'typeorm';

// UPPERCASE columns (raw SQL) — auth/employee APIs use unquoted uppercase identifiers
export class CreateAccountAndEmployeeHistoryTables20260128000002 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // ACCOUNT table
    await queryRunner.query(`CREATE SEQUENCE ACCOUNT_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE`);
    await queryRunner.query(`
      CREATE TABLE ACCOUNT (
        ID NUMBER DEFAULT ACCOUNT_ID_SEQ.NEXTVAL PRIMARY KEY,
        EMPLOYEE_ID NUMBER NOT NULL,
        USERNAME VARCHAR2(50) NOT NULL,
        PASSWORD_HASH VARCHAR2(200) NOT NULL,
        ROLE VARCHAR2(20) DEFAULT 'USER' NOT NULL,
        IS_ACTIVE NUMBER DEFAULT 1 NOT NULL,
        LAST_LOGIN_AT TIMESTAMP,
        PASSWORD_CHANGED_AT TIMESTAMP,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        DELETED_AT TIMESTAMP
      )
    `);
    await queryRunner.query(`ALTER TABLE ACCOUNT ADD CONSTRAINT CHK_ACCOUNT_ROLE CHECK (ROLE IN ('ADMIN', 'MANAGER', 'USER'))`);
    await queryRunner.query(`ALTER TABLE ACCOUNT ADD CONSTRAINT UQ_ACCOUNT_USERNAME UNIQUE (USERNAME)`);
    await queryRunner.query(`ALTER TABLE ACCOUNT ADD CONSTRAINT FK_ACCOUNT_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID)`);
    await queryRunner.query(`CREATE INDEX IDX_ACCOUNT_EMPLOYEE_ID ON ACCOUNT(EMPLOYEE_ID)`);
    await queryRunner.query(`CREATE INDEX IDX_ACCOUNT_DELETED_AT ON ACCOUNT(DELETED_AT)`);

    // EMPLOYEE_HISTORY table
    await queryRunner.query(`CREATE SEQUENCE EMPLOYEE_HISTORY_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE`);
    await queryRunner.query(`
      CREATE TABLE EMPLOYEE_HISTORY (
        ID NUMBER DEFAULT EMPLOYEE_HISTORY_ID_SEQ.NEXTVAL PRIMARY KEY,
        EMPLOYEE_ID NUMBER NOT NULL,
        CHANGE_TYPE VARCHAR2(50) NOT NULL,
        CHANGED_FIELDS CLOB NOT NULL,
        CHANGED_BY_ID NUMBER NOT NULL,
        CHANGED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
      )
    `);
    await queryRunner.query(`ALTER TABLE EMPLOYEE_HISTORY ADD CONSTRAINT FK_EMP_HISTORY_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID)`);
    await queryRunner.query(`ALTER TABLE EMPLOYEE_HISTORY ADD CONSTRAINT FK_EMP_HISTORY_CHANGED_BY FOREIGN KEY (CHANGED_BY_ID) REFERENCES EMPLOYEE(ID)`);
    await queryRunner.query(`CREATE INDEX IDX_EMP_HISTORY_EMP_ID ON EMPLOYEE_HISTORY(EMPLOYEE_ID)`);
    await queryRunner.query(`CREATE INDEX IDX_EMP_HISTORY_CHANGED_AT ON EMPLOYEE_HISTORY(CHANGED_AT)`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IDX_EMP_HISTORY_CHANGED_AT`);
    await queryRunner.query(`DROP INDEX IDX_EMP_HISTORY_EMP_ID`);
    await queryRunner.query(`ALTER TABLE EMPLOYEE_HISTORY DROP CONSTRAINT FK_EMP_HISTORY_CHANGED_BY`);
    await queryRunner.query(`ALTER TABLE EMPLOYEE_HISTORY DROP CONSTRAINT FK_EMP_HISTORY_EMPLOYEE`);
    await queryRunner.query(`DROP TABLE EMPLOYEE_HISTORY`);
    await queryRunner.query(`DROP SEQUENCE EMPLOYEE_HISTORY_ID_SEQ`);

    await queryRunner.query(`DROP INDEX IDX_ACCOUNT_DELETED_AT`);
    await queryRunner.query(`DROP INDEX IDX_ACCOUNT_EMPLOYEE_ID`);
    await queryRunner.query(`ALTER TABLE ACCOUNT DROP CONSTRAINT FK_ACCOUNT_EMPLOYEE`);
    await queryRunner.query(`ALTER TABLE ACCOUNT DROP CONSTRAINT UQ_ACCOUNT_USERNAME`);
    await queryRunner.query(`DROP TABLE ACCOUNT`);
    await queryRunner.query(`DROP SEQUENCE ACCOUNT_ID_SEQ`);
  }
}
