// Generated: 2026-01-24 01:00:00 KST

import { MigrationInterface, QueryRunner } from 'typeorm';

// UPPERCASE columns (raw SQL) — employee/auth APIs use unquoted uppercase identifiers
// POSITION must exist before this migration (position_id FK)
export class CreateEmployeeTable20260125020000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE SEQUENCE EMPLOYEE_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE`);

    await queryRunner.query(`
      CREATE TABLE EMPLOYEE (
        ID NUMBER DEFAULT EMPLOYEE_ID_SEQ.NEXTVAL PRIMARY KEY,
        NAME VARCHAR2(100) NOT NULL,
        EMAIL VARCHAR2(100) NOT NULL,
        PHONE VARCHAR2(20),
        JOB_TITLE VARCHAR2(100),
        DEPARTMENT_ID NUMBER NOT NULL,
        POSITION_ID NUMBER NOT NULL,
        MANAGER_ID NUMBER,
        HIRED_AT DATE NOT NULL,
        BIRTHDAY DATE,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CREATED_BY_ID NUMBER,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_BY_ID NUMBER,
        DELETED_AT TIMESTAMP
      )
    `);

    await queryRunner.query(`ALTER TABLE EMPLOYEE ADD CONSTRAINT UQ_EMPLOYEE_EMAIL UNIQUE (EMAIL)`);
    await queryRunner.query(`ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)`);
    await queryRunner.query(`ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_POSITION FOREIGN KEY (POSITION_ID) REFERENCES POSITION(ID)`);
    await queryRunner.query(`ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE(ID)`);
    await queryRunner.query(`ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_CREATED_BY FOREIGN KEY (CREATED_BY_ID) REFERENCES EMPLOYEE(ID)`);
    await queryRunner.query(`ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_UPDATED_BY FOREIGN KEY (UPDATED_BY_ID) REFERENCES EMPLOYEE(ID)`);
    await queryRunner.query(`CREATE INDEX IDX_EMPLOYEE_DELETED_AT ON EMPLOYEE(DELETED_AT)`);
    await queryRunner.query(`CREATE INDEX IDX_EMPLOYEE_DEPARTMENT_ID ON EMPLOYEE(DEPARTMENT_ID)`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IDX_EMPLOYEE_DEPARTMENT_ID`);
    await queryRunner.query(`DROP INDEX IDX_EMPLOYEE_DELETED_AT`);
    await queryRunner.query(`ALTER TABLE EMPLOYEE DROP CONSTRAINT FK_EMPLOYEE_UPDATED_BY`);
    await queryRunner.query(`ALTER TABLE EMPLOYEE DROP CONSTRAINT FK_EMPLOYEE_CREATED_BY`);
    await queryRunner.query(`ALTER TABLE EMPLOYEE DROP CONSTRAINT FK_EMPLOYEE_MANAGER`);
    await queryRunner.query(`ALTER TABLE EMPLOYEE DROP CONSTRAINT FK_EMPLOYEE_POSITION`);
    await queryRunner.query(`ALTER TABLE EMPLOYEE DROP CONSTRAINT FK_EMPLOYEE_DEPARTMENT`);
    await queryRunner.query(`ALTER TABLE EMPLOYEE DROP CONSTRAINT UQ_EMPLOYEE_EMAIL`);
    await queryRunner.query(`DROP TABLE EMPLOYEE`);
    await queryRunner.query(`DROP SEQUENCE EMPLOYEE_ID_SEQ`);
  }
}
