// Generated: 2026-03-07 21:30:00 KST

import { MigrationInterface, QueryRunner } from 'typeorm';

// Drops and recreates INVENTORY, INVENTORY_HISTORY with UPPERCASE columns
// to match the inventory API which uses unquoted uppercase identifiers.
// Previous migration created them with quoted lowercase columns — incompatible.
export class RecreateInventoryTables20260307000001 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // Drop old tables
    await queryRunner.query(`DROP TABLE INVENTORY_HISTORY CASCADE CONSTRAINTS PURGE`);
    await queryRunner.query(`DROP TABLE INVENTORY CASCADE CONSTRAINTS PURGE`);

    // Drop old sequences
    await queryRunner.query(`DROP SEQUENCE INVENTORY_SEQ`);
    await queryRunner.query(`DROP SEQUENCE INVENTORY_HISTORY_SEQ`);

    // Recreate sequences
    await queryRunner.query(`CREATE SEQUENCE INVENTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE`);
    await queryRunner.query(`CREATE SEQUENCE INVENTORY_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE`);

    // INVENTORY table — UPPERCASE unquoted columns
    await queryRunner.query(`
      CREATE TABLE INVENTORY (
        ID NUMBER DEFAULT INVENTORY_SEQ.NEXTVAL PRIMARY KEY,
        CATEGORY VARCHAR2(50) NOT NULL,
        MODEL VARCHAR2(255) NOT NULL,
        SERIAL_NUMBER VARCHAR2(100) NOT NULL,
        PURCHASE_DATE DATE NOT NULL,
        PURCHASE_FROM VARCHAR2(255) NOT NULL,
        CURRENT_LOCATION VARCHAR2(255) NOT NULL,
        CURRENT_STATUS VARCHAR2(20) DEFAULT '재고' NOT NULL,
        NOTES CLOB,
        CREATED_BY_ID NUMBER NOT NULL,
        UPDATED_BY_ID NUMBER NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        DELETED_AT TIMESTAMP
      )
    `);
    await queryRunner.query(`ALTER TABLE INVENTORY ADD CONSTRAINT CHK_INVENTORY_STATUS CHECK (CURRENT_STATUS IN ('재고', '출고', '고장', '폐기'))`);
    await queryRunner.query(`ALTER TABLE INVENTORY ADD CONSTRAINT UQ_INVENTORY_SERIAL UNIQUE (SERIAL_NUMBER)`);
    await queryRunner.query(`ALTER TABLE INVENTORY ADD CONSTRAINT FK_INVENTORY_CREATED_BY FOREIGN KEY (CREATED_BY_ID) REFERENCES EMPLOYEE(ID)`);
    await queryRunner.query(`ALTER TABLE INVENTORY ADD CONSTRAINT FK_INVENTORY_UPDATED_BY FOREIGN KEY (UPDATED_BY_ID) REFERENCES EMPLOYEE(ID)`);
    await queryRunner.query(`CREATE INDEX IDX_INVENTORY_STATUS ON INVENTORY(CURRENT_STATUS)`);
    await queryRunner.query(`CREATE INDEX IDX_INVENTORY_CATEGORY ON INVENTORY(CATEGORY)`);
    await queryRunner.query(`CREATE INDEX IDX_INVENTORY_LOCATION ON INVENTORY(CURRENT_LOCATION)`);
    await queryRunner.query(`CREATE INDEX IDX_INVENTORY_MODEL ON INVENTORY(MODEL)`);
    await queryRunner.query(`CREATE INDEX IDX_INVENTORY_CREATED_AT ON INVENTORY(CREATED_AT)`);
    await queryRunner.query(`CREATE INDEX IDX_INVENTORY_DELETED_AT ON INVENTORY(DELETED_AT)`);

    // INVENTORY_HISTORY table — UPPERCASE unquoted columns
    await queryRunner.query(`
      CREATE TABLE INVENTORY_HISTORY (
        ID NUMBER DEFAULT INVENTORY_HISTORY_SEQ.NEXTVAL PRIMARY KEY,
        INVENTORY_ID NUMBER NOT NULL,
        CHANGE_TYPE VARCHAR2(20) NOT NULL,
        PREVIOUS_LOCATION VARCHAR2(255),
        NEW_LOCATION VARCHAR2(255),
        PREVIOUS_STATUS VARCHAR2(20),
        NEW_STATUS VARCHAR2(20),
        CHECKOUT_LOCATION VARCHAR2(255),
        EXPECTED_CHECKIN_DATE DATE,
        REASON VARCHAR2(500),
        CHANGED_BY_ID NUMBER NOT NULL,
        CHANGED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
      )
    `);
    await queryRunner.query(`ALTER TABLE INVENTORY_HISTORY ADD CONSTRAINT FK_INV_HISTORY_INVENTORY FOREIGN KEY (INVENTORY_ID) REFERENCES INVENTORY(ID)`);
    await queryRunner.query(`ALTER TABLE INVENTORY_HISTORY ADD CONSTRAINT FK_INV_HISTORY_CHANGED_BY FOREIGN KEY (CHANGED_BY_ID) REFERENCES EMPLOYEE(ID)`);
    await queryRunner.query(`CREATE INDEX IDX_INV_HISTORY_INV ON INVENTORY_HISTORY(INVENTORY_ID)`);
    await queryRunner.query(`CREATE INDEX IDX_INV_HISTORY_AT ON INVENTORY_HISTORY(CHANGED_AT)`);
    await queryRunner.query(`CREATE INDEX IDX_INV_HISTORY_TYPE ON INVENTORY_HISTORY(CHANGE_TYPE)`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IDX_INV_HISTORY_TYPE`);
    await queryRunner.query(`DROP INDEX IDX_INV_HISTORY_AT`);
    await queryRunner.query(`DROP INDEX IDX_INV_HISTORY_INV`);
    await queryRunner.query(`ALTER TABLE INVENTORY_HISTORY DROP CONSTRAINT FK_INV_HISTORY_CHANGED_BY`);
    await queryRunner.query(`ALTER TABLE INVENTORY_HISTORY DROP CONSTRAINT FK_INV_HISTORY_INVENTORY`);
    await queryRunner.query(`DROP TABLE INVENTORY_HISTORY`);

    await queryRunner.query(`DROP INDEX IDX_INVENTORY_DELETED_AT`);
    await queryRunner.query(`DROP INDEX IDX_INVENTORY_CREATED_AT`);
    await queryRunner.query(`DROP INDEX IDX_INVENTORY_MODEL`);
    await queryRunner.query(`DROP INDEX IDX_INVENTORY_LOCATION`);
    await queryRunner.query(`DROP INDEX IDX_INVENTORY_CATEGORY`);
    await queryRunner.query(`DROP INDEX IDX_INVENTORY_STATUS`);
    await queryRunner.query(`ALTER TABLE INVENTORY DROP CONSTRAINT FK_INVENTORY_UPDATED_BY`);
    await queryRunner.query(`ALTER TABLE INVENTORY DROP CONSTRAINT FK_INVENTORY_CREATED_BY`);
    await queryRunner.query(`ALTER TABLE INVENTORY DROP CONSTRAINT UQ_INVENTORY_SERIAL`);
    await queryRunner.query(`DROP TABLE INVENTORY`);

    await queryRunner.query(`DROP SEQUENCE INVENTORY_HISTORY_SEQ`);
    await queryRunner.query(`DROP SEQUENCE INVENTORY_SEQ`);
  }
}
