// Generated: 2026-03-07 21:00:00 KST

import { MigrationInterface, QueryRunner } from 'typeorm';

// Drops and recreates ISSUE, ISSUE_ATTACHMENT, ISSUE_HISTORY with UPPERCASE
// columns to match the issues API which uses unquoted uppercase identifiers.
// Previous migration created them with quoted lowercase columns — incompatible.
export class RecreateIssueTables20260307000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // Drop old tables (CASCADE handles FK constraints)
    await queryRunner.query(`DROP TABLE ISSUE_HISTORY CASCADE CONSTRAINTS PURGE`);
    await queryRunner.query(`DROP TABLE ISSUE_ATTACHMENT CASCADE CONSTRAINTS PURGE`);
    await queryRunner.query(`DROP TABLE ISSUE CASCADE CONSTRAINTS PURGE`);

    // Drop old sequences (will recreate)
    await queryRunner.query(`DROP SEQUENCE ISSUE_SEQ`);
    await queryRunner.query(`DROP SEQUENCE ISSUE_ATTACHMENT_SEQ`);
    await queryRunner.query(`DROP SEQUENCE ISSUE_HISTORY_SEQ`);

    // Recreate sequences
    await queryRunner.query(`CREATE SEQUENCE ISSUE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE`);
    await queryRunner.query(`CREATE SEQUENCE ISSUE_ATTACHMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE`);
    await queryRunner.query(`CREATE SEQUENCE ISSUE_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE`);

    // ISSUE table — UPPERCASE unquoted columns
    await queryRunner.query(`
      CREATE TABLE ISSUE (
        ID NUMBER DEFAULT ISSUE_SEQ.NEXTVAL PRIMARY KEY,
        CUSTOMER_ID NUMBER NOT NULL,
        TITLE VARCHAR2(255) NOT NULL,
        DESCRIPTION CLOB,
        SEVERITY VARCHAR2(20) DEFAULT 'CRITICAL' NOT NULL,
        STATUS VARCHAR2(20) DEFAULT 'INTAKE' NOT NULL,
        IS_PUBLIC NUMBER DEFAULT 0 NOT NULL,
        CREATED_BY_ID NUMBER NOT NULL,
        ASSIGNED_TO_ID NUMBER,
        TREATMENT_METHOD VARCHAR2(20),
        TREATMENT_TIME_MINUTES NUMBER,
        TREATMENT_RESULT CLOB,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        COMPLETED_AT TIMESTAMP,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        DELETED_AT TIMESTAMP
      )
    `);
    await queryRunner.query(`ALTER TABLE ISSUE ADD CONSTRAINT CHK_ISSUE_SEVERITY CHECK (SEVERITY IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW'))`);
    await queryRunner.query(`ALTER TABLE ISSUE ADD CONSTRAINT CHK_ISSUE_STATUS CHECK (STATUS IN ('INTAKE', 'IN_PROGRESS', 'COMPLETED'))`);
    await queryRunner.query(`ALTER TABLE ISSUE ADD CONSTRAINT CHK_ISSUE_TREATMENT_METHOD CHECK (TREATMENT_METHOD IS NULL OR TREATMENT_METHOD IN ('REMOTE', 'PHONE', 'ONSITE'))`);
    await queryRunner.query(`ALTER TABLE ISSUE ADD CONSTRAINT FK_ISSUE_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER("id")`);
    await queryRunner.query(`ALTER TABLE ISSUE ADD CONSTRAINT FK_ISSUE_CREATED_BY FOREIGN KEY (CREATED_BY_ID) REFERENCES EMPLOYEE(ID)`);
    await queryRunner.query(`ALTER TABLE ISSUE ADD CONSTRAINT FK_ISSUE_ASSIGNED FOREIGN KEY (ASSIGNED_TO_ID) REFERENCES EMPLOYEE(ID)`);
    await queryRunner.query(`CREATE INDEX IDX_ISSUE_CUSTOMER ON ISSUE(CUSTOMER_ID)`);
    await queryRunner.query(`CREATE INDEX IDX_ISSUE_STATUS ON ISSUE(STATUS)`);
    await queryRunner.query(`CREATE INDEX IDX_ISSUE_ASSIGNED ON ISSUE(ASSIGNED_TO_ID)`);
    await queryRunner.query(`CREATE INDEX IDX_ISSUE_DELETED_AT ON ISSUE(DELETED_AT)`);
    await queryRunner.query(`CREATE INDEX IDX_ISSUE_CREATED_AT ON ISSUE(CREATED_AT)`);

    // ISSUE_ATTACHMENT table — UPPERCASE unquoted columns
    await queryRunner.query(`
      CREATE TABLE ISSUE_ATTACHMENT (
        ID NUMBER DEFAULT ISSUE_ATTACHMENT_SEQ.NEXTVAL PRIMARY KEY,
        ISSUE_ID NUMBER NOT NULL,
        FILE_NAME VARCHAR2(200) NOT NULL,
        FILE_PATH VARCHAR2(500) NOT NULL,
        FILE_SIZE NUMBER NOT NULL,
        UPLOADED_BY_ID NUMBER NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        DELETED_AT TIMESTAMP
      )
    `);
    await queryRunner.query(`ALTER TABLE ISSUE_ATTACHMENT ADD CONSTRAINT FK_ISSUE_ATTACH_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES ISSUE(ID)`);
    await queryRunner.query(`ALTER TABLE ISSUE_ATTACHMENT ADD CONSTRAINT FK_ISSUE_ATTACH_UPLOADER FOREIGN KEY (UPLOADED_BY_ID) REFERENCES EMPLOYEE(ID)`);
    await queryRunner.query(`CREATE INDEX IDX_ISSUE_ATTACH_ISSUE ON ISSUE_ATTACHMENT(ISSUE_ID)`);
    await queryRunner.query(`CREATE INDEX IDX_ISSUE_ATTACH_DELETED ON ISSUE_ATTACHMENT(DELETED_AT)`);

    // ISSUE_HISTORY table — UPPERCASE unquoted columns
    await queryRunner.query(`
      CREATE TABLE ISSUE_HISTORY (
        ID NUMBER DEFAULT ISSUE_HISTORY_SEQ.NEXTVAL PRIMARY KEY,
        ISSUE_ID NUMBER NOT NULL,
        CHANGE_TYPE VARCHAR2(50) NOT NULL,
        OLD_VALUE CLOB,
        NEW_VALUE CLOB,
        CHANGED_BY_ID NUMBER NOT NULL,
        CHANGED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        REMARK VARCHAR2(500)
      )
    `);
    await queryRunner.query(`ALTER TABLE ISSUE_HISTORY ADD CONSTRAINT FK_ISSUE_HISTORY_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES ISSUE(ID)`);
    await queryRunner.query(`ALTER TABLE ISSUE_HISTORY ADD CONSTRAINT FK_ISSUE_HISTORY_CHANGER FOREIGN KEY (CHANGED_BY_ID) REFERENCES EMPLOYEE(ID)`);
    await queryRunner.query(`CREATE INDEX IDX_ISSUE_HISTORY_ISSUE ON ISSUE_HISTORY(ISSUE_ID)`);
    await queryRunner.query(`CREATE INDEX IDX_ISSUE_HISTORY_AT ON ISSUE_HISTORY(CHANGED_AT)`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IDX_ISSUE_HISTORY_AT`);
    await queryRunner.query(`DROP INDEX IDX_ISSUE_HISTORY_ISSUE`);
    await queryRunner.query(`ALTER TABLE ISSUE_HISTORY DROP CONSTRAINT FK_ISSUE_HISTORY_CHANGER`);
    await queryRunner.query(`ALTER TABLE ISSUE_HISTORY DROP CONSTRAINT FK_ISSUE_HISTORY_ISSUE`);
    await queryRunner.query(`DROP TABLE ISSUE_HISTORY`);

    await queryRunner.query(`DROP INDEX IDX_ISSUE_ATTACH_DELETED`);
    await queryRunner.query(`DROP INDEX IDX_ISSUE_ATTACH_ISSUE`);
    await queryRunner.query(`ALTER TABLE ISSUE_ATTACHMENT DROP CONSTRAINT FK_ISSUE_ATTACH_UPLOADER`);
    await queryRunner.query(`ALTER TABLE ISSUE_ATTACHMENT DROP CONSTRAINT FK_ISSUE_ATTACH_ISSUE`);
    await queryRunner.query(`DROP TABLE ISSUE_ATTACHMENT`);

    await queryRunner.query(`DROP INDEX IDX_ISSUE_CREATED_AT`);
    await queryRunner.query(`DROP INDEX IDX_ISSUE_DELETED_AT`);
    await queryRunner.query(`DROP INDEX IDX_ISSUE_ASSIGNED`);
    await queryRunner.query(`DROP INDEX IDX_ISSUE_STATUS`);
    await queryRunner.query(`DROP INDEX IDX_ISSUE_CUSTOMER`);
    await queryRunner.query(`ALTER TABLE ISSUE DROP CONSTRAINT FK_ISSUE_ASSIGNED`);
    await queryRunner.query(`ALTER TABLE ISSUE DROP CONSTRAINT FK_ISSUE_CREATED_BY`);
    await queryRunner.query(`ALTER TABLE ISSUE DROP CONSTRAINT FK_ISSUE_CUSTOMER`);
    await queryRunner.query(`DROP TABLE ISSUE`);

    await queryRunner.query(`DROP SEQUENCE ISSUE_HISTORY_SEQ`);
    await queryRunner.query(`DROP SEQUENCE ISSUE_ATTACHMENT_SEQ`);
    await queryRunner.query(`DROP SEQUENCE ISSUE_SEQ`);
  }
}
