-- ============================================================
-- 2101_001_create_notice_tables.sql
-- 공지사항 모듈 테이블 생성
-- Generated: 2026-01-28 16:00:00 KST
-- ============================================================

-- ============================================================
-- 1. NOTICE 테이블 (게시물)
-- ============================================================

CREATE TABLE NOTICE (
    ID                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TITLE             VARCHAR2(200) NOT NULL,
    CONTENT           CLOB NOT NULL,
    TYPE              VARCHAR2(20) NOT NULL,
    AUTHOR_ID         NUMBER NOT NULL,
    VIEW_COUNT        NUMBER DEFAULT 0 NOT NULL,
    UPDATED_BY_ID     NUMBER,
    DELETION_REASON   VARCHAR2(500),
    "created_at"      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    "updated_at"      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    "deleted_at"      TIMESTAMP,

    -- Check Constraint: 게시판 유형
    CONSTRAINT NOTICE_TYPE_CHK CHECK (TYPE IN ('공지', '공유', '지시', '건의', '자유')),

    -- Foreign Keys (ON DELETE RESTRICT is default in Oracle)
    CONSTRAINT NOTICE_AUTHOR_FK FOREIGN KEY (AUTHOR_ID)
        REFERENCES EMPLOYEE(ID),
    CONSTRAINT NOTICE_UPDATED_BY_FK FOREIGN KEY (UPDATED_BY_ID)
        REFERENCES EMPLOYEE(ID)
);

-- 테이블 코멘트
COMMENT ON TABLE NOTICE IS '공지사항 게시물';
COMMENT ON COLUMN NOTICE.ID IS '게시물 ID (자동 생성)';
COMMENT ON COLUMN NOTICE.TITLE IS '제목 (5~200자)';
COMMENT ON COLUMN NOTICE.CONTENT IS '내용 (10~10,000자)';
COMMENT ON COLUMN NOTICE.TYPE IS '게시판 유형 (공지/공유/지시/건의/자유)';
COMMENT ON COLUMN NOTICE.AUTHOR_ID IS '작성자 ID (FK: EMPLOYEE)';
COMMENT ON COLUMN NOTICE.VIEW_COUNT IS '조회수';
COMMENT ON COLUMN NOTICE.UPDATED_BY_ID IS '수정자 ID (FK: EMPLOYEE, nullable)';
COMMENT ON COLUMN NOTICE.DELETION_REASON IS '삭제 사유 (nullable)';
COMMENT ON COLUMN NOTICE."created_at" IS '생성일시';
COMMENT ON COLUMN NOTICE."updated_at" IS '수정일시';
COMMENT ON COLUMN NOTICE."deleted_at" IS '삭제일시 (soft delete)';

-- ============================================================
-- 2. NOTICE_COMMENT 테이블 (댓글/답글)
-- Note: COMMENT is Oracle reserved word, using NOTICE_COMMENT
-- ============================================================

CREATE TABLE NOTICE_COMMENT (
    ID                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOTICE_ID           NUMBER NOT NULL,
    CONTENT             VARCHAR2(1000) NOT NULL,
    AUTHOR_ID           NUMBER NOT NULL,
    PARENT_COMMENT_ID   NUMBER,
    "created_at"        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    "updated_at"        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    "deleted_at"        TIMESTAMP,

    -- Foreign Keys
    CONSTRAINT NC_NOTICE_FK FOREIGN KEY (NOTICE_ID)
        REFERENCES NOTICE(ID),
    CONSTRAINT NC_AUTHOR_FK FOREIGN KEY (AUTHOR_ID)
        REFERENCES EMPLOYEE(ID),
    CONSTRAINT NC_PARENT_FK FOREIGN KEY (PARENT_COMMENT_ID)
        REFERENCES NOTICE_COMMENT(ID)
);

-- 테이블 코멘트
COMMENT ON TABLE NOTICE_COMMENT IS '공지사항 댓글/답글';
COMMENT ON COLUMN NOTICE_COMMENT.ID IS '댓글 ID (자동 생성)';
COMMENT ON COLUMN NOTICE_COMMENT.NOTICE_ID IS '게시물 ID (FK: NOTICE)';
COMMENT ON COLUMN NOTICE_COMMENT.CONTENT IS '댓글 내용 (1~1000자)';
COMMENT ON COLUMN NOTICE_COMMENT.AUTHOR_ID IS '작성자 ID (FK: EMPLOYEE)';
COMMENT ON COLUMN NOTICE_COMMENT.PARENT_COMMENT_ID IS '부모 댓글 ID (답글용, 최대 2단계)';
COMMENT ON COLUMN NOTICE_COMMENT."created_at" IS '생성일시';
COMMENT ON COLUMN NOTICE_COMMENT."updated_at" IS '수정일시';
COMMENT ON COLUMN NOTICE_COMMENT."deleted_at" IS '삭제일시 (soft delete, Notice 삭제 시 cascade)';

-- ============================================================
-- 3. NOTICE_ATTACHMENT 테이블 (첨부파일)
-- ============================================================

CREATE TABLE NOTICE_ATTACHMENT (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOTICE_ID       NUMBER NOT NULL,
    FILENAME        VARCHAR2(255) NOT NULL,
    FILE_PATH       VARCHAR2(500) NOT NULL,
    FILE_SIZE       NUMBER NOT NULL,
    MIME_TYPE       VARCHAR2(100) NOT NULL,
    UPLOADED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    "deleted_at"    TIMESTAMP,

    -- Check Constraint: 파일 크기 (최대 10MB)
    CONSTRAINT NOTICE_ATTACH_SIZE_CHK CHECK (FILE_SIZE <= 10485760),

    -- Foreign Keys
    CONSTRAINT NOTICE_ATTACH_NOTICE_FK FOREIGN KEY (NOTICE_ID)
        REFERENCES NOTICE(ID)
);

-- 테이블 코멘트
COMMENT ON TABLE NOTICE_ATTACHMENT IS '공지사항 첨부파일';
COMMENT ON COLUMN NOTICE_ATTACHMENT.ID IS '첨부파일 ID (자동 생성)';
COMMENT ON COLUMN NOTICE_ATTACHMENT.NOTICE_ID IS '게시물 ID (FK: NOTICE)';
COMMENT ON COLUMN NOTICE_ATTACHMENT.FILENAME IS '원본 파일명';
COMMENT ON COLUMN NOTICE_ATTACHMENT.FILE_PATH IS '저장 경로 (UUID 기반)';
COMMENT ON COLUMN NOTICE_ATTACHMENT.FILE_SIZE IS '파일 크기 (bytes, 최대 10MB)';
COMMENT ON COLUMN NOTICE_ATTACHMENT.MIME_TYPE IS 'MIME 타입 (매직 바이트 검증)';
COMMENT ON COLUMN NOTICE_ATTACHMENT.UPLOADED_AT IS '업로드 일시';
COMMENT ON COLUMN NOTICE_ATTACHMENT."deleted_at" IS '삭제일시 (soft delete, Notice 삭제 시 cascade)';
