-- Fix NOTICE_TYPE_CHK constraint with proper Korean encoding
ALTER TABLE NOTICE DROP CONSTRAINT NOTICE_TYPE_CHK;
ALTER TABLE NOTICE ADD CONSTRAINT NOTICE_TYPE_CHK CHECK (TYPE IN ('공지', '공유', '지시', '건의', '자유'));
COMMIT;
